language: python
python: 2.7
sudo: false
cache:
  directories:
  - ../build/plonetheme.mytheme/eggs
install:
- nvm install 6
- pip install mr.bob
- mrbob -O ../build -c .travis-plone-$PLONE.ini .
script:
- make -C ../build/plonetheme.mytheme
env:
- PLONE=5.0.5
- PLONE=5.0.6
- PLONE=5.0.7
- PLONE=5.0-latest
