language: python
python: 2.7
sudo: false
cache:
  directories:
  - ../build/plonetheme.mytheme/eggs
install:
- nvm install 6
- pip install mr.bob
- mrbob -O ../build -c .travis-plone-5.0.5.ini .
script:
- make -C ../build/plonetheme.mytheme
